buildscript {
    repositories {
        // mavenLocal()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath "org.graceframework:grace-gradle-plugin:$graceVersion"
        classpath "io.github.gradle-nexus:publish-plugin:2.0.0"
    }
}

ext."signing.keyId" = project.hasProperty("signing.keyId") ? project.getProperty('signing.keyId') : System.getenv('SIGNING_KEY')
ext."signing.password" = project.hasProperty("signing.password") ? project.getProperty('signing.password') : System.getenv('SIGNING_PASSPHRASE')
ext."signing.secretKeyRingFile" = project.hasProperty("signing.secretKeyRingFile") ? project.getProperty('signing.secretKeyRingFile') : ("${System.properties['user.home']}${File.separator}.gnupg${File.separator}secring.gpg")
ext.isReleaseVersion = !projectVersion.endsWith("SNAPSHOT")

version = projectVersion
group = "org.graceframework.profiles"

apply plugin: "eclipse"
apply plugin: "idea"
apply plugin: "groovy"
apply plugin: "org.graceframework.grace-doc"
apply plugin: "org.graceframework.grace-profile"
apply plugin: "io.github.gradle-nexus.publish-plugin"
apply plugin: "maven-publish"
apply plugin: "signing"

repositories {
    // mavenLocal()
    mavenCentral()
    maven {
        name = 'Maven Central Portal Snapshots'
        url = 'https://central.sonatype.com/repository/maven-snapshots/'

        content {
            includeGroupAndSubgroups 'org.graceframework'
        }
        mavenContent {
            snapshotsOnly()
        }
    }
}

dependencies {
    // implementation "org.codehaus.groovy:groovy:$groovyVersion"
    profile "org.graceframework.profiles:base:$baseVersion"
}

tasks.withType(Sign) {
   onlyIf { isReleaseVersion }
}

tasks.withType(GroovyCompile) {
    configure(groovyOptions) {
        forkOptions.jvmArgs = ['-Xmx1024m']
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
    withJavadocJar()
    withSourcesJar()
}

jar {
    manifest.mainAttributes(
        "Built-By": System.properties['user.name'],
        "Created-By": System.properties['java.vm.version'] + " (" + System.properties['java.vm.vendor'] + ")",
        "Implementation-Title": "Grace Plugin Profile",
        "Implementation-Version": project.version,
        "Implementation-Vendor": 'graceframework.org')
}

processProfileResources {
    commandsDir = project.layout.projectDirectory.dir('app/commands')
    featuresDir = project.layout.projectDirectory.dir('app/features')
    skeletonDir = project.layout.projectDirectory.dir('src/main/skeleton')
    templatesDir = project.layout.projectDirectory.dir('src/main/templates')
}

compileProfile {
    source = project.layout.projectDirectory.dir('app/commands')
    featuresDir = project.layout.projectDirectory.dir('app/features')
    templatesDir = project.layout.projectDirectory.dir('src/main/templates')
}

tasks.register('docs') {
    dependsOn publishGuide
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = project.group
            artifactId = project.name
            version = project.version

            from components.java

            afterEvaluate {
                artifact source: "${project.buildDir}/classes/profile/META-INF/grails-profile/profile.yml",
                        classifier: 'profile',
                        extension: 'yml'
            }
            pom {
                name = "Grace Plugin Profile"
                description = "A Grace profile to create plugin"
                url = 'https://github.com/grace-profiles/plugin'
                licenses {
                    license {
                        name = 'The Apache License, Version 2.0'
                        url = 'https://www.apache.org/licenses/LICENSE-2.0.txt'
                    }
                }
                developers {
                    developer {
                        id = 'rainboyan'
                        name = 'Michael Yan'
                        email = 'rain@rainboyan.com'
                    }
                }
                scm {
                    connection = 'scm:git:git://github.com/grace-profiles/plugin.git'
                    developerConnection = 'scm:git:ssh://github.com:grace-profiles/plugin.git'
                    url = 'https://github.com/grace-profiles/plugin'
                }
            }
        }
    }
}

nexusPublishing {
    repositories {
        sonatype {
            def mavenUser = System.getenv("MAVEN_CENTRAL_USER") ?: project.hasProperty("mavenCentralUsername") ? project.mavenCentralUsername : ''
            def mavenPass = System.getenv("MAVEN_CENTRAL_PASSWORD") ?: project.hasProperty("mavenCentralPassword") ? project.mavenCentralPassword : ''
            nexusUrl = uri("https://ossrh-staging-api.central.sonatype.com/service/local/")
            snapshotRepositoryUrl = uri("https://central.sonatype.com/repository/maven-snapshots/")
            username = mavenUser
            password = mavenPass
        }
    }
}

afterEvaluate {
    signing {
        required = isReleaseVersion && gradle.taskGraph.hasTask("publish")
        sign publishing.publications.maven
    }
}
