plugins {
@buildPlugins@
}

group = "@grace.app.group@"

repositories {
@repositories@
}

configurations {
    developmentOnly
}

dependencies {
    developmentOnly "org.springframework.boot:spring-boot-devtools"
@dependencies@
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.withType(GroovyCompile) {
    configure(groovyOptions) {
        forkOptions.jvmArgs = ['-Xmx1024m']
    }
}

tasks.withType(Test) {
    useJUnitPlatform()
}
